### ISSUE TITLE
Please Stop 2: Electric Boogaloo

### ISSUE THREAD

**Issue by DylanGTech** [RochesterJournalist/DylanGreenRIT#2]
Might I please have the names, social media accounts, and status at RIT for the creators of this project? I would like to create a similar repository. There are legal ways of finding out, but I would prefer not to do so.

To answer your question about making friends, which you deleted after having been called put:

I have also multiple friends who you accuse me of wanting to kill:l (according to this repository and your website):  3 are Jewish, one of which is at RIT. 1 of which is a former homosexual. Another is a present-day homosexual, but is still finding his way. I may bring them on here soon to say the same "hate speech" I say if you so wish.

**Comment by RochesterJournalist** [comment]
Hello again Dylan,

We responded to your previous issue report and then closed it, but you misunderstood and thought it was deleted. No harm done though, understandably the Github interface can be a bit overwhelming the first couple of times you use it.

To restate what was said on the previous issue, we will not provide any names or other personal information to you, so there is not need to keep asking.

It is a bit funny to see that after we closed your previous issue you called for people on Gab to brigade our repository; especially given you seem fond of your own freedom of speech. I guess we know how far your principles extend (see photo below).
![cap](https://user-images.githubusercontent.com/91993216/143958708-21c8fc4a-fec2-40c0-afd5-eb3968c8bdf5.jpg)

Again, if anything is not factual with the information in this repo, or on our website, please feel free to open a new issue. We will take down any non-factual information as soon as we are made aware of it.

Once again, we wish you well!

**Comment by DylanGTech** [comment]
All of your accusations are lies. Here's a list of them:

> He supports things like
> - The Taliban
> - Homophobia
> - Anti-Semitism
> And he is seeking a job potentially with the US government.

Next up:

> Dylan Green is an RIT student currently seeking a job as a software engineer. He also has some pretty hateful views...

Continuing on:
> He has recently tried to bury all of this so that recruiters would not see it
> Here is a selection of things that were either posted or re-posted by Dylan Green on Gab which he has tried to hide specifically because he doesn’t want recruiters seeing it

Here are a few more false claims:
> You left out that by opposing gay marriage you mean they throw gays off of rooftops
> Nice implication that gays were all raped as children

These are all false claims about me. Take them all down right now, please.

**Comment by RochesterJournalist** [comment]
Those are all factual, but it can be hard to keep track of social media posts you made so allow me to provide evidence:

> He supports things like
> - The Taliban
[Post Supporting The Taliban](https://dylangtech.net/images/3.png)
> - Homophobia
[Homophobic Post](https://dylangtech.net/images/4.png)
> - Anti-Semitism
[Antisemitic post](https://dylangtech.net/images/2.png)
> And he is seeking a job potentially with the US government.

`"I might be deactivating this account for some time. Seeing as I might be about to receive a government job, this account existing could compromise a lot during that time."`

> Dylan Green is an RIT student currently seeking a job as a software engineer. He also has some pretty hateful views...

See pretty much any of the previous images

> He has recently tried to bury all of this so that recruiters would not see it

Again: `"I might be deactivating this account for some time. Seeing as I might be about to receive a government job, this account existing could compromise a lot during that time."`

> Here is a selection of things that were either posted or re-posted by Dylan Green on Gab which he has tried to hide specifically because he doesn’t want recruiters seeing it

Again: `"I might be deactivating this account for some time. Seeing as I might be about to receive a government job, this account existing could compromise a lot during that time."`

> You left out that by opposing gay marriage you mean they throw gays off of rooftops

Not sure what you are really saying is not factual here, but you have in fact expressed support of the Taliban's treatment of gay people, and given that that generally is extreme violence and genocide anyone is free to connect the dots as to what you are implying.
[More Taliban support](https://dylangtech.net/images/5.png)

> Nice implication that gays were all ***** as children

[Stonetoss Comic](https://dylangtech.net/images/4.png)
